# Generated by Django 4.1.4 on 2023-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmagics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('done_by', models.CharField(default='unknown', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='netmagicsadmin',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
