# Generated by Django 4.2.2 on 2023-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmagics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmagicsadmin',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
