# Generated by Django 4.1.4 on 2023-09-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('estd_date', models.DateField(default='9999-99-99')),
                ('is_suspend', models.BooleanField(default=False)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_lawfirms', to='userapp.advocate')),
            ],
        ),
    ]
