# Generated by Django 4.1.4 on 2023-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='estd_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
