# Generated by Django 4.1.4 on 2023-09-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_advocate_document_image_and_more'),
        ('lawfirm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lawfirms', to='userapp.advocate'),
        ),
    ]
