# Generated by Django 4.1.4 on 2023-09-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0004_advocatelawfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocatelawfirm',
            name='lawfirm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm'),
        ),
    ]
