# Generated by Django 4.1.4 on 2023-09-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0005_advocatelawfirm_lawfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocatelawfirm',
            name='lawfirm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm'),
        ),
    ]
