# Generated by Django 4.1.4 on 2023-09-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('estd_date', models.DateField(default='9999-99-99')),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('is_suspend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('estd_date', models.DateField(default='9999-99-99')),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFineAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('unit_of_plan', models.CharField(max_length=20)),
                ('membership_price', models.CharField(default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('association', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.court')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(max_length=300)),
                ('payment_expiry_date', models.DateField(default='2020-07-20')),
                ('payment_total_amount_paid', models.IntegerField(default=0)),
                ('payment_requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.membershipplan')),
                ('payment_requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationMembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_done_at', models.DateField(auto_now_add=True)),
                ('payment_expiry_date', models.DateField(default='2020-07-20')),
                ('payment_total_amount_paid', models.IntegerField(default=0)),
                ('payment_status_of_gateway', models.CharField(default='failed', max_length=25)),
                ('for_payment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.membershipplan')),
                ('for_user_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useradvocate', to='userapp.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.court'),
        ),
    ]
