# Generated by Django 4.1.4 on 2023-09-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembershippayment',
            name='payment_association',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='associationpaymentrequest',
            name='payment_association',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='membershipfineamount',
            name='association',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='association',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterField(
            model_name='association',
            name='estd_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='associationmembershippayment',
            name='payment_expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='associationpaymentrequest',
            name='payment_expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='court',
            name='estd_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.CreateModel(
            name='AssociationSuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(default='not given', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_owner', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_status', models.BooleanField(default=False)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.advocate')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association')),
            ],
        ),
    ]
