# Generated by Django 4.1.4 on 2023-09-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_userdata_name'),
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembershippayment',
            name='payment_association',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='associationpaymentrequest',
            name='payment_association',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='membershipfineamount',
            name='association',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='association',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.CreateModel(
            name='AdvocateAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_status', models.BooleanField(default=False)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.advocate')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association')),
            ],
        ),
    ]
