# Generated by Django 4.2.2 on 2023-09-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0002_associationmembershippayment_payment_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateassociation',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='advocateassociation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advocateassociation',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
