# Generated by Django 4.1.4 on 2023-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_associationmembershippayment_payment_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='estd_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='associationmembershippayment',
            name='payment_expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='associationpaymentrequest',
            name='payment_expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='court',
            name='estd_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
