# Generated by Django 4.2.2 on 2023-09-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_advocateassociation_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateassociation',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
