# Generated by Django 4.1.4 on 2023-09-10 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0004_associationadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssociationAdmin',
            new_name='AssociationSuperAdmin',
        ),
    ]
