# Generated by Django 4.2.2 on 2023-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_advocateassociation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateassociation',
            name='description',
            field=models.CharField(blank=True, default='Not given', max_length=100, null=True),
        ),
    ]
