# Generated by Django 4.1.4 on 2023-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='type_of_user',
            field=models.CharField(choices=[('normal_advocate', 'Normal Advocate'), ('normal_admin', 'Normal Admin'), ('super_admin', 'Super Admin'), ('registrar', 'Registrar')], default='normal_user', max_length=255),
        ),
    ]
