# Generated by Django 4.1.4 on 2023-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_advocate_document_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='type_of_user',
            field=models.CharField(choices=[('normal_advocate', 'Normal Advocate'), ('normal_admin', 'Normal Admin'), ('super_admin', 'Super Admin'), ('registrar', 'Registrar')], default='normal_advocate', max_length=255),
        ),
    ]
