# Generated by Django 4.1.4 on 2023-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_advocate_document_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='age',
        ),
        migrations.AddField(
            model_name='advocate',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
