# Generated by Django 4.1.4 on 2023-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_userdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='type_of_user',
            field=models.CharField(choices=[('normal_advocate', 'Normal Advocate'), ('normal_admin', 'Normal Admin'), ('super_admin', 'Super Admin')], default='normal_advocate', max_length=255),
        ),
    ]
