# Generated by Django 4.1.4 on 2023-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_advocate_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
