# Generated by Django 4.1.4 on 2023-09-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_registrar_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='type_of_user',
        ),
    ]
