# Generated by Django 4.1.4 on 2023-09-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityTracker',
        ),
    ]
